<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="css/index.css" />
		<script
			src="https://kit.fontawesome.com/48b5735cbc.js"
			crossorigin="anonymous"
		></script>
		<title>Food Store</title>
	</head>
	<body>
		<div class="top-bar">
			<img
				src="https://static.vecteezy.com/system/resources/previews/000/656/608/original/vector-restaurant-badge-and-logo-good-for-print.jpg"
				alt="logo"
			/>
			<div class="navbar">
				<a class="pressing-btn" href="#">Trang chủ</a>
				<a href="intro.php">Giới thiệu</a>
				<a href="table.php">Đặt bàn</a>
				<a href="menu.php">Thực đơn</a>
				<a href="news.php">Tin tức</a>
				<a href="contact.php">Liên hệ</a>
			</div>
			<i class="fa-solid fa-bars" onclick="toggleMenu();"></i>
		</div>
	</div>

	<div class="intro-img">
		<div class="intro-food">
			<img
			src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/SLIDER2.jpg"
			alt=""
			/>
			<img 
			src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/fzn_0370_ll12.jpg" 
			alt=""
			/>
			<img 
			src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/menu.jpg" 
			alt=""
			/>
			<button onclick="plusIndex(-1)"><i class="fa-solid fa-angle-left i-1stl"></i></button>
			<button onclick="plusIndex(1)"><i class="fa-solid fa-angle-right i-1str"></i></button>
		</div>
		<div class="intro-price">
			<img
				src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/bang-gia-01-1024x165.png"
				alt=""
			/>
		</div>
		
		<div class="bbq">
			<div class="text-box">
				<h1>Sun Homes BBQ</h1>
				<p>
					Sun Homes BBQ (Quán thịt nướng Hàn Quốc) sẽ đưa bạn đến Seoul, nơi
					những con phố bình dị, những quán ăn dân dã đã trở nên quen thuộc và
					gắn bó với người dân xứ Hàn. Nếu đã một lần thưởng thức thịt nướng tại
					Sun Homes BBQ, bạn sẽ không thể quên được hương vị “ngất ngây” của
					những món sườn non bò Mỹ, nạc vai bò Mỹ, dẻ sườn tươi…. khi hòa quyện
					vào với các loại gia vị đặc trưng của xứ sở Kimchi đã trở nên hấp dẫn
					đến thế nào.
					<br />
					<br />
					Bí quyết của Sun Homes BBQ nằm ở nước sốt tẩm ướp thịt được chế biến
					từ nguyên liệu hoàn toàn tự nhiên, theo công thức bí truyền, do Bếp
					Trưởng Park Sung Min hơn 40 năm kinh nghiệm nghiên cứu và chế biến.
					Sun Homes BBQ có 2 dạng thực đơn để Quý Khách lựa chọn là: Chọn Combo
					và Gọi Món.
				</p>
			</div>
			<div class="img-box">
				<img
					src="https://th.bing.com/th/id/OIP.8D7xniYbR3poVPLL6-sNwQAAAA?pid=ImgDet&rs=1"
					alt=""
				/>
			</div>
			<div class="img-box">
				<img
					src="https://th.bing.com/th/id/OIP.RMewTysWflvPbRGH8wD66gHaEl?pid=ImgDet&rs=1"
					alt=""
				/>
			</div>
		</div>

		<div class="menu">
			<div class="img-box-2">
				<img
					src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/1212.jpg"
					alt=""
				/>
				<img
					src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/fzn_0496_ll-900x598-300x199.jpg"
					alt=""
				/>
				<img
					src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/4534545345.jpg"
					alt=""
				/>
				<img
					src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/fzn_0370_ll12-1.jpg"
					alt=""
				/>
			</div>
			<div class="text-box-2">
				<h1>Menu</h1>
				<p>
					Hơn 200 món ăn được chắt lọc từ Tinh hoa ẩm thực Hàn Quốc với mức giá
					chỉ từ 69.000 cùng nhiều combo và set bộ hấp dẫn đều có trong menu của
					King BBQ. Ngoài ra các bạn còn được thưởng thức những món ăn đặc trưng
					và nổi tiếng trong văn hoá ẩm thực của Hàn Quốc do chính tay đàu bếp
					người Hàn Quốc chế biến.
				</p>
				<button><i class="fa-solid fa-bag-shopping"></i>Thực đơn</button>
			</div>
		</div>

		<div class="restaurant">
			<div class="text-box-4">
				<h1>Restaurant</h1>
				<p>
					Khi nói đến Hàn Quốc, ẩm thực là nét văn hóa đặc trưng không thể bỏ
					qua và thịt nướng Hàn Quốc luôn được “truyền tai” về độ tươi ngon, đậm
					đà qua những trang cẩm nang du lịch hay những bộ phim Hàn gây bão.
				</p>
				<p>
					Hệ thống Sun Homes BBQ hiện có 17 nhà hàng trong đó 7 nhà hàng chuyên
					về Buffet tự chọn (Buffet) và 10 nhà hàng chuyên về gọi món
					(Alacarte).
				</p>
				<p>Hãy lựa chọn địa điểm gần bạn nhất và liên hệ đặt bàn ngay nhé!</p>
				<button>
					<i class="fa-solid fa-magnifying-glass"></i><b>Nhà hàng</b>
				</button>
			</div>
			<div class="img-box-4">
				<img
					src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/nha-hang-king-bbq-1-2-679x1024.jpg"
					alt=""
				/>
				<img
					src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/nha-hang-king-bbq-1-1-679x1024.jpg"
					alt=""
				/>
			</div>
		</div>

		<div class="sign-up">
			<p>Đăng ký để nhận ưu đãi hàng tháng tới 30% từ Sun Homes BBQ</p>
			<input type="text" placeholder="  Nhập địa chỉ email..." />
			<button><b>Đăng ký ngay</b></button>
		</div>

		<div class="cousin">
			<div class="top-cousin">
				<div class="img-box-5">
					<img
						src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/213854-set-menu-han-quoc-hap-dan-danh-cho-2-nguoi-suon-nuong-han-quoc.jpg"
						alt=""
					/>
				</div>
				<div class="text-box-5">
					<h1>Korea Cousin</h1>
					<p>
						Khi nói đến Hàn Quốc, ẩm thực là nét văn hóa đặc trưng không thể
						bỏ qua và thịt nướng Hàn Quốc luôn được “truyền tai” về độ tươi
						ngon, đậm đà qua những trang cẩm nang du lịch hay những bộ phim
						Hàn gây bão.
					</p>
					<p>
						Sốt chấm Ssamjang cay nồng thường được dùng để ăn kèm với các loại
						thịt nướng. Đó là hỗn hợp được trộn giữa tương đậu và tương ớt lên
						men..mỗi khi thịt chín ruộm, người ta phết một chút sốt lên bề mặt
						miếng thịt, cuộn cùng với kim chi, xà lách xoăn, dưa chuột. Cho
						tất cả vào miệng và nhai kỹ bạn sẽ cảm nhận được ngay hương vị đặc
						biệt của loại tương này.
					</p>
				</div>
			</div>

			<div class="bottom-cousin">
				<img
					src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/cach-an-thit-nuong-2.jpg"
					alt=""
				/>
				<img
					src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/img20161208034438844.jpg"
					alt=""
				/>
				<img
					src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/1-11-2014-6-05-19-PM.jpg"
					alt=""
				/>
				<img
					src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/images.jpg"
					alt=""
				/>
			</div>
		</div>

		<div class="order">
            <div class="text-box-3">
                <h1>Set Table</h1>
                <p class="no-num">
                    Quý khách vui lòng đặt bàn trước để có trải nghiệm thưởng thức ẩm thực
                    tốt nhất tại Sun Homes BBQ.
                </p>
                <p class="no-num">
                    <u><i>Sau khi đặt bàn nhà hàng sẽ liên hệ lại để xác thực</i></u>
                </p>
                <p>
                    <i class="fa-solid fa-angle-right i-2nd"></i> Để chắc chắn bàn đã được đặt gọi trực
                    tiếp Hotline: 0909.009.009
                </p>
                <hr />
            </div>

			<div class="infor">
                <form method="post" action="">
                    <input type="text" placeholder="Tên của bạn..." name="customer_name" required/>
                    <input type="text" placeholder="Số điện thoại..." name="phone" required/>
                    <input type="number" placeholder="Số người ăn..." name="number_people" required/>
                    <input type="datetime-local" name="time_reserve" required/>
                    <button type="submit" name="reserve_table"><b>ĐẶT BÀN</b></button>
                </form>
			</div>
		</div>

		<div class="donor">
			<img src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/macgicc.png" alt=""/>
			<img src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/cbjc.png" alt=""/>
			<img src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/logo-cbs-2.png" alt=""/>
			<img src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/asm_color-1.png" alt=""/>
			<img src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/hutong_color.png" alt=""/>
			<img src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/3cc_color.png" alt=""/>
			<img src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/0d6208722f020705340d841f32286ef1a01f2c196a291bc368-pimgpsh_fullsize_distr.png" alt=""/>
			<img src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/gogic.png" alt=""/>
			<img src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/itachocoloe.png" alt=""/>
			<img src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/icookc.png" alt=""/>
		</div>

		<script>	
			var slideIndexIntro = 0;
			var slideIndexDonor = 0;
			var arrImgIntro = document.querySelectorAll('.intro-food > img');
			var arrImgDonor = document.querySelectorAll('.donor img');

			function plusIndex(n) {
				showSlideIntro(slideIndexIntro + n);
			}

			function showSlideIntro(n) {				
				slideIndexIntro = n;

				if (n >= arrImgIntro.length) slideIndexIntro = 0;
				if (n < 0) slideIndexIntro = arrImgIntro.length - 1;

				for (let i = 0; i < arrImgIntro.length; i++) {
					arrImgIntro[i].style.display = 'none';
				}

				arrImgIntro[slideIndexIntro].style.display = 'block';
			}

			function showSlideDonor() {
				const len = arrImgDonor.length;

				for (let i = 0; i < len; i++) {
					arrImgDonor[i].style.display = 'none';
				}

				const x = len - slideIndexDonor;
				if (x < 6) {
					for (let i = slideIndexDonor; i < len; i++) {
						arrImgDonor[i].style.display = 'block';
						arrImgDonor[i].style.order = i - slideIndexDonor + 1;
					}

					for (let i = 0; i < 6 - x; i++) {
						arrImgDonor[i].style.display = 'block';
						arrImgDonor[i].style.order = i + len - slideIndexDonor + 1;
					}
				} else {
					for (let i = slideIndexDonor; i < slideIndexDonor + 6; i++) {
						arrImgDonor[i].style.display = 'block';
						arrImgDonor[i].style.order = i - slideIndexDonor + 1;
					}
				}
				
			}

			showSlideIntro(slideIndexIntro);
			setInterval(() => {
				slideIndexDonor++;
				if (slideIndexDonor >= arrImgDonor.length) slideIndexDonor = 0;
				showSlideDonor();
			}, 2000);	
			
			const toggleMenu = () => {
				const menu = document.querySelector('.navbar');

				if (menu.style.visibility == 'hidden') {
					menu.style.visibility = 'visible';
				} else {
					menu.style.visibility = 'hidden';
				}
			}
		</script>
	</body>
</html>
