<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="css/intro.css" />
		<script
			src="https://kit.fontawesome.com/48b5735cbc.js"
			crossorigin="anonymous"
		></script>
		<title>Food Store</title>
	</head>
	<body>
		<div class="top-bar">
			<img
				src="https://static.vecteezy.com/system/resources/previews/000/656/608/original/vector-restaurant-badge-and-logo-good-for-print.jpg"
				alt="logo"
			/>
			<div class="navbar">
				<a href="index.php">Trang chủ</a>
				<a class="pressing-btn" href="#">Giới thiệu</a>
				<a href="order.php">Đặt bàn</a>
				<a href="menu.php">Thực đơn</a>
				<a href="news.php">Tin tức</a>
				<a href="contact.php">Liên hệ</a>
			</div>
			<i class="fa-solid fa-bars" onclick="toggleMenu();"></i>
		</div>

		<div class="first-img">
			<img
				src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/banner-234.jpg"
				alt=""
			/>
		</div>

		<div class="description">
			<div class="left">
				<h1><b>SUN HOMES ALACARTE (GỌI MÓN)</b></h1>
				<img
					src="https://bizhostvn.com/w/bbq/wp-content/uploads/2018/02/concept-1.jpg"
					alt=""
				/>
				<br />
				<p>
					<b>Sun Homes BBQ</b> là mô hình phục vụ các món ăn gọi riêng lẻ theo nhu cầu.
					Mỗi món tương ứng với giá tiền khác nhau. King BBQ mô hình gọi món,
					với thực đơn đa dạng hơn 200 món ăn cùng các set bộ và combo dành cho
					2-4 người với mức giá hợp lý. Món sườn King là món ăn đặc trưng và rất
					nổi tiếng mà bất cứ thực khách nào đến King BBQ cũng không thể bỏ qua.
				</p>
				<br />
				<p>
					<b>Sun Homes BBQ</b> là điểm đến cho các khách hàng có nhu cầu tiếp khách, tụ
					tập bạn bè, gia đình, liên hoan sinh nhật.
				</p>
				<button><i class="fa-solid fa-magnifying-glass"></i><b>Thực đơn</b></button>
			</div>

			<div class="right">
				<h1><b>SUN HOMES ALACARTE (GỌI MÓN)</b></h1>
				<img
					src="https://bizhostvn.com/w/bbq/wp-content/uploads/2018/02/king.jpg"
					alt=""
				/>
				<br />
				<p>
					<b>Sun Homes BBQ</b> là mô hình Buffet tự chọn ăn không giới hạn trong một
					mức giá cố định, có Line Buffet để quý khách lựa chọn món ăn. Quý
					khách có thể bắt đầu bằng các món soup, kimchi salad, món nóng, món cổ
					truyền, các món thịt tẩm sốt Hàn Quốc nướng trên than hồng, và kết
					thúc với món tráng miệng. Thực đơn Buffet hơn 200 món ăn đa dạng đặc
					trưng hương vị Hàn Quốc.
				</p>
				<br />
				<p>
					<b>Sun Homes BBQ</b> đặc biệt thích hợp với khách hàng có nhu cầu tổ chức
					liên hoan sinh nhật, khách đoàn và gia đình.
				</p>
				<button><i class="fa-solid fa-heart"></i><b>Thực đơn</b></button>
			</div>
		</div>

		<script>
			const toggleMenu = () => {
				const menu = document.querySelector('.navbar');
				if (menu.style.visibility == 'hidden') menu.style.visibility = 'visible';
				else menu.style.visibility = 'hidden';
			}
		</script>
	</body>
</html>
