<?php
use Controller\DishController;
$controller = new DishController();
//$dishes = $controller->getAllEvent();
//$dishes= $controller->getAllDish();

$dishes= $controller->getAllDishByCategory('khai_vi');


if (isset($_SERVER['REQUEST_METHOD']) && $_SERVER['REQUEST_METHOD'] == 'GET') {
    if (isset($_GET['khai_vi'])) {
        $dishes= $controller->getAllDishByCategory('khai_vi');
        $isChoseOne = true;
        $isChoseTwo = false;
        $isChoseThree = false;
    } else if (isset($_GET['mon_chinh'])) {
        $dishes = $controller->getAllDishByCategory('mon_chinh');
        $isChoseOne = false;
        $isChoseTwo = true;
        $isChoseThree = false;
    } else if (isset($_GET['trang_mieng'])) {
        $dishes= $controller->getAllDishByCategory('trang_mieng');
        $isChoseOne = false;
        $isChoseTwo = false;
        $isChoseThree = true;
    }
}
//$dishes_chinh = $controller->getDishByCategory('mon_chinh');
//var_dump($dishes) ;

?>
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="css/menu.css" />
		<script
			src="https://kit.fontawesome.com/48b5735cbc.js"
			crossorigin="anonymous"
		></script>
		<title>Food Store</title>
	</head>
	<body>
		<div class="top-bar">
			<img
				src="https://static.vecteezy.com/system/resources/previews/000/656/608/original/vector-restaurant-badge-and-logo-good-for-print.jpg"
				alt="logo"
			/>
			<div class="navbar">
				<a href="index.php">Trang chủ</a>
				<a href="intro.php">Giới thiệu</a>
				<a href="table.php">Đặt bàn</a>
				<a class="pressing-btn" href="#">Thực đơn</a>
				<a href="news.php">Tin tức</a>
				<a href="contact.php">Liên hệ</a>
			</div>
      <i class="fa-solid fa-bars" onclick="toggleMenu();"></i>
		</div>

		<div class="first-img">
			<img
				src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/banner-234.jpg"
				alt=""
			/>
		</div>

		<div class="wrap">
			<h1>THỰC ĐƠN TẠI HÀ NỘI</h1>

            <form method="get" class="dish-form" action="./menu.php">
                <ul>
                    <li><button class="<?php echo $isChoseOne ? 'activated' : ''?>" type="submit" name="khai_vi" id="khai_vi" onclick="show('khai_vi')">Món khai vị</button></li>
                    <li><button class="<?php echo $isChoseTwo ? 'activated' : ''?>" type="submit" type="submit" name="mon_chinh" id="mon_chinh" onclick="show('mon_chinh')">Món chính</button></li>
                    <li><button class="<?php echo $isChoseThree ? 'activated' : ''?>" type="submit" type="submit" name="trang_mieng" id="trang_mieng" onclick="show('trang_mieng')">Món tráng miệng</button></li>
                </ul>
            </form>


			<div class="combos">
        <p>* Áp dụng cho tất cả các ngày trong tuần</p>
                <?php
                    foreach ($dishes as $dish) {
                        echo "<div class='combo'>
                <div class='col-inner'>
                    <img
                      src='".$dish['image_url']."'
                      alt=''
                    />
                    <h1>".$dish['name']."</h1>
                    <p><i class='fa-solid fa-check'></i>".$dish['description']."</p>                 
                </div>
			</div>";
                    }
                ?>
		</div>

		<script type="text/javascript">
			const links = document.querySelectorAll('ul li a');
			for (let i = 0; i < links.length; i++) {
				links[i].onclick = () => {
					const activated = document.querySelectorAll('.activated');
					for (let i = 0; i < activated.length; i++) {
						activated[i].classList.remove('activated');
					}

					links[i].classList.add('activated');
				};
			}

			const toggleMenu = () => {
				const menu = document.querySelector('.navbar');
				if (menu.style.visibility == 'hidden') menu.style.visibility = 'visible';
				else menu.style.visibility = 'hidden';
			}

            // function show(category) {
            //     document.getElementById('khai_vi').className = '';
            //     document.getElementById('mon_chinh').className = '';
            //     document.getElementById('trang_mieng').className = '';
            //     document.getElementById(category).className = 'activated';
            //
            //
            // }
		</script>
	</body>
</html>
