<?php

namespace View\Bill;
use Controller\BillController;
use Controller\DishController;

session_start();
if(isset($_SESSION["staff"])){
    $staff = $_SESSION["staff"];
}else{
    header('Location: index.php');
}

$billController = new BillController();
$dishController = new DishController();
$bills = $billController->getAllBill();
$dishs = $dishController->getAllDish();

?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="./css/style.css">
    <link rel="stylesheet" href="./css/Bill.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <title>Admin Page</title>
</head>
<body>

<div class = "page">
    <header class="header-wrapper">
        <div class="header-group">
            <button class="btn-open-sidebar" onclick="openSide()">☰</button>
            <label>BABA RESTO</label>
        </div>

        <div class="header-group" onclick="handleClickOnUser()">
            <i class='fa-solid fa-user icon-user'></i>
            <span class="header-identity">
                <?php echo $staff[0]['name'];?>
                <div class="user-info" id="user-info">
                    <p><a href="./ChangePasswordForm.php">Đổi mật khẩu</a></p>
                    <p><a href="./index.php">Đăng xuất</a></p>
                </div>
            </span>
        </div>
    </header>
    <div class="container">
        <aside class="sidebar-wrapper">
            <a href="./Table.php" class="sidebar-link">
                <i class="fa-solid fa-table"></i>
                Quản lý Bàn
            </a>
            <a href="./Bill.php" class="sidebar-link active">
                <i class="fa-solid fa-money-bill"></i>
                Quản lý Hóa đơn
            </a>
            <a href="Dish.php" class="sidebar-link">
                <i class="fa-solid fa-utensils"></i>
                Quản lý Món ăn
            </a>
            <a href="./Event.php" class="sidebar-link">
                <i class="fa-solid fa-calendar-check"></i>
                Quản lý Sự kiện
            </a>
            <a href="Report.php" class="sidebar-link">
                <i class="fa-solid fa-chart-column"></i>
                Thống kê kinh doanh
            </a>
        </aside>
        
        <div class="content">
          <div class="wrapper">
            <button class="add-bill" onclick="showAddBillForm()">Add Bill</button>
            <div class="bill-list">             
                <?php
                  echo "<table>
                          <tr>
                            <th class='bill_id'>Mã hóa đơn</th>
                            <th class='bill_id'>Tên KH</th>
                            <th class='discount_rate'>Giảm giá(%)</th>
                            <th class='time_create'>Ngày nhập</th>
                            <th class='total'>Tổng tiền</th>
                            <th class='status'>Trạng thái</th>
                          </tr>";
                  foreach ($bills as $index => $bill) {
                    echo "<tr>";
                    echo "<td>".$bill['bill_id']."</td>";
                    echo "<td>".$bill['guest_name']."</td>";
                    $discount = ($bill['discount_rate'] == ""||$bill['discount_rate']==0)? "Không" : $bill['discount_rate'];
                    echo "<td>".$discount."</td>";
                    echo "<td>".$bill['time_create']."</td>";
                    echo "<td>".$bill['total']."</td>";
                    $stt = $bill['status'] == 1 ? "Đã thanh toán" : "Chưa thanh toán";
                    echo "<td>".$stt."</td>";
                    echo "</tr>";
                  }
                  echo "</table>";
                ?>
            </div>
          </div>
          <div class="add-bill-layout" id="bill-layout">
            <div class="add-wrapper">
              <button class="exit-button" onclick="handleExit()">x</button>
              <form action="" id="bill-form" method='POST' autocomplete="off">
                <p>
                  <span>Tên Khách Hàng:</span>
                  <input id='guest_name' type="text" name="guest_name"><br>
                </p>
                <p>
                  <span>Số điện thoại:</span>
                  <input id='guest_phone' type="text" name="guest_phone">
                </p>
                <p>
                  <span>Giảm giá:</span>
                  <input id='discount_rate' type="text" name="discount_rate">
                </p>
                <table id='tableId'>
                  <tr>
                    <th>Tên món</th>
                    <th>Đơn giá</th>
                    <th>Số lượng</th>
                    <th>Thành tiền</th>
                  </tr>
                  <tr onchange="changeSum(this)">
                    <td onclick="changePrice(this)"><input type="text" class="dish_id" name="dish_id" id="dish_id" ></td>
                    <td><input type="text" id="don_gia" name="don_gia" ></td>
                    <td><input type="text" class="dish_quantity" name="dish_quantity"></td>
                    <td><input type="text" id="sum" name="sum" readonly></td>
                  </tr>
                  <input type="text" name="total" style="visibility:hidden" id="total">
                </table>

                      <button type='button' onclick=addInputRow() class="add_btn-row">+</button>
                      <button class="add-button" id="add-button" name="add" onclick="changeTotal()">Add</button>
              </form>
            </div>
          </div>
        </div>
    </div>
</div>

<script>

    var lis = [
      <?php
        foreach ($dishs as $index => $dish) {
          echo "'$dish[name]',";
        }
      ?>
    ];

    var priceArr = [
      <?php
        foreach ($dishs as $index => $dish) {
          echo "'$dish[price]',";
        }
      ?>
    ];

    function addInputRow() {
      table = document.getElementById("tableId");
      row = table.insertRow(-1);
      row.setAttribute("onchange", "changeSum(this)");
      cell1 = row.insertCell(0);
      cell1.setAttribute("onclick", "changePrice(this)")
      cell2 = row.insertCell(1);
      cell3 = row.insertCell(2); 
      cell4 = row.insertCell(3);
      cell1.innerHTML = '<input type="text" class="diss_id" name="dish_id" id="dish_id">';
      cell2.innerHTML = '<input type="text" class="don_gia" name="don_gia" >';
      cell3.innerHTML = '<input type="text" class="dish_quantity" name="dish_quantity">';
      cell4.innerHTML = '<input type="text" id="sum" name="sum" readonly>'

      autocomplete(cell1.firstElementChild, lis);
    }

    function showAddBillForm() {
      form = document.getElementById("bill-layout");
      form.style.display="block";
    }

    function handleExit() {
      form = document.getElementById("bill-layout");
      form.style.display="none";
    }

    function changeSum(obj) {
      let tdNodes = obj.children;
      let donGia = tdNodes[1].firstElementChild.value;
      let soLuong = tdNodes[2].firstElementChild.value;
      let thanhTien = donGia*soLuong;
      tdNodes[3].firstElementChild.setAttribute("value", thanhTien);

    }

    function changePrice(obj) {
      let nextSibling = obj.nextElementSibling;
      let name=obj.firstElementChild.value;
      let idx = lis.indexOf(name);
      nextSibling.firstElementChild.setAttribute("value", priceArr[idx]);
      console.log(nextSibling,idx,name);
    }

    function changeTotal() {
      var arr = document.getElementsByName('sum');
      var discount = document.getElementById('discount_rate').value;
      var tot=0;
      for(var i=0;i<arr.length;i++){
          if(parseInt(arr[i].value))
              tot += parseInt(arr[i].value);
      }
      if (discount > 0) tot = (int)(tot*(100-discount)/100);
      document.getElementById('total').value = tot;
      console.log(tot);
    }

</script>
<script>
    function openSide(){
        const sidebar = document.getElementById("sidebar");
        sidebar.classList.add("sidebar-active") ;

        window.addEventListener("mouseup", function(event) {
            if (event.target != sidebar) {
                sidebar.classList.remove("sidebar-active");
            }
        });

        window.addEventListener("resize", () =>{
            if(window.innerWidth > 414){
                sidebar.classList.add("sidebar-active") ;
            }
        });
    }

    function handleClickOnUser() {
        const user = document.getElementById('user-info');
        if (user.style.display == "none") {
            user.style.display = "block";
            document.getElementById('container').style.opacity = 0.3;
            return;
        }
        user.style.display = "none";
        document.getElementById('container').style.opacity = 1;
    }
</script>
<script src="./View/javascript/autocomplete.js"></script>
</body>
</html>