<?php

session_start();
if(isset($_SESSION["staff"])){
    $staff = $_SESSION["staff"];
//    var_dump($staff);
}else{
    header('Location: Login.php');
}
?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="./css/style.css">
    <link rel="stylesheet" href="./css/ChangePasswordForm.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <title>Document</title>
</head>
<body>

  <div class = "page">
    <header class="header-wrapper">
        <label>BABA RESTO</label>

        <div class="header-group" onclick="handleClickOnUser()">
            <i class='fa-solid fa-user icon-user'></i>
            <span class="header-identity">
                <?php echo $staff[0]['name'];?>
                <div class="user-info" id="user-info">
                    <p><a href="./ChangePasswordForm.php">Doi mat khau</a></p>
                    <p><a href="./index.php">Dang xuat</a></p>
                </div>
            </span>          
        </div>  
    </header>
    <div class="container">
        <aside class="sidebar-wrapper">
            <a href="Table.php" class="sidebar-link">
                <i class="fa-solid fa-table"></i>
                Quản lý Bàn
            </a>
            <a href="#" class="sidebar-link">
                <i class="fa-solid fa-money-bill"></i>
                Quản lý Hóa đơn
            </a>
            <a href="Dish.php" class="sidebar-link">
                <i class="fa-solid fa-utensils"></i>
                Quản lý Món ăn
            </a>
            <a href="./Event.php" class="sidebar-link">
                <i class="fa-solid fa-calendar-check"></i>
                Quản lý Sự kiện
            </a>
            <a href="Report.php" class="sidebar-link">
                <i class="fa-solid fa-chart-column"></i>
                Thống kê kinh doanh
            </a>
        </aside>
        <div class="content">
          <div class="wrapper">
            <p class="title">Đổi mật khẩu</p>
            <form action="" method="POST">
              <div class="content-input">
                <label for="old-pass">Mật khẩu cũ:</label>
                <input type="password" id="old-pass"/>
              </div>
              <div class="content-input">
                <label for="new-pass">Mật khẩu mới:</label>
                <input type="password" id="new-pass"/>
              </div>
              <div class="content-input">
                <label for="rewrite-new-pass">Nhập lại mật khẩu mới:</label>
                <input type="password" id="rewrite-old-pass"/>
              </div>
              <button type="submit" name="change_password">OK</button>
            </form>
          </div>
        </div>
    </div>   
</body>
</html>