<?php

namespace View\Event;
use Controller\EventController;
session_start();
if(isset($_SESSION["staff"])){
    $staff = $_SESSION["staff"];
//    var_dump($staff);
}else{
    header('Location: Login.php');
}

$eventController = new EventController();
$events = $eventController->getAllEvent();
?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="./css/style.css">
    <link rel="stylesheet" href="./css/Event.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <title>Admin Page</title>
</head>
<body>

<div class="page">
    <header class="header-wrapper">
        <div class="header-group">
            <button class="btn-open-sidebar" onclick="openSide()">☰</button>
            <label> Tên nhà hàng</label>
        </div>

        <div class="header-group" onclick="handleClickOnUser()" id="header-group">
            <i class='fa-solid fa-user icon-user'></i>
            <span class="header-identity">
                <?php echo $staff[0]['name'];?>
                <div class="user-info" id="user-info">
                    <p><a href="./ChangePasswordForm.php">Đổi mật khẩu</a></p>
                    <p><a href="./index.php">Đăng xuất</a></p>
                </div>
            </span>          
        </div>  
    </header>
    <div class="container" id="container">
        <aside class="sidebar-wrapper" id="sidebar">
            <label>Danh mục quản lý</label>
            <a href="Table.php" class="sidebar-link">
                <i class="fa-solid fa-table"></i>
                Quản lý Bàn
            </a>
            <a href="Bill.php" class="sidebar-link">
                <i class="fa-solid fa-money-bill"></i>
                Quản lý Hóa đơn
            </a>
            <a href="Dish.php" class="sidebar-link">
                <i class="fa-solid fa-utensils"></i>
                Quản lý Món ăn
            </a>
            <a href="Event.php" class="sidebar-link active">
                <i class="fa-solid fa-calendar-check"></i>
                Quản lý Sự kiện
            </a>
            <a href="Report.php" class="sidebar-link">
                <i class="fa-solid fa-chart-column"></i>
                Thống kê kinh doanh
            </a>
        </aside>
        <div class="content">
          <div class="wrapper">
            <button class="add-event" onclick="addEvent()">Thêm sự kiện</button>
            <div class="event-list">             
                <?php
                  echo "<table>
                          <tr>
                            <th class='title'>Tiêu đề</th>
                            <th class='description collapse'>Mô tả</th>
                            <th class='img_link'>Hình ảnh</th>
                            <th class='changebtn'></th>
                          </tr>";
                  foreach ($events as $index => $event) {
                    echo "<tr>";
                    echo "<td>".$event['title']."</td>";
                    echo "<td class='collapse'>".$event['description']."</td>";
                    echo "<td><img src='".$event['image_link']."' /></td>";
                    echo "<td>
                            <button class='editbtn' onclick='editEvent(".$event['event_id'].")'>Sửa</button>
                            <button class='deletebtn' onclick='deleteEvent(".$event['event_id'].")'>Xóa</button>
                          </td>";
                    echo "</tr>";
                  }
                  echo "</table>";
                ?>
            </div>
          </div>
          <div class="add-event-layout" id="event-form">
            <div class="add-wrapper">
                <button class="exit_add" onclick="exitAdd()">X</button>
                <form action="./Event.php" method="POST">
                      <div class="new" id="event-id">
                        <label>Id sự kiện:</label>
                        <span id="event-id-to-edit"></span>
                        <input type="text" id="eventId" name="eventId" style="visibility:hidden" />
                      </div>
                      <div class="new">
                          <label for="title">Tiêu đề</label>
                          <input type="text" id="title" name="title" />
                      </div>
                      <div class="new">
                          <label for="description">Mô tả</label>
                          <textarea id="description" name="description"></textarea>
                      </div>
                      <div class="new">
                          <label for="img_link">Link hình ảnh</label>
                          <input type="text" id="img_link" name="imgLink" />
                      </div>
                      <button class="agree-add" type="submit" name="add" id="addbtn">Thêm</button>
                      <button class="agree-add" type="submit" name="update" id="updatebtn">Sửa</button>
                </form>
            </div>
          </div>
          <div class="add-event-layout" id="form-to-del">
            <div class="add-wrapper">
                <button class="exit_add" onclick="exitDel()">X</button>
                <form action="./Event.php" method="POST"> 
                    <input type="text" id="eventId2" name="eventId2" style="visibility:hidden" />
                    <p>Bạn chắc chắn muốn xóa sự kiện này?</p>
                    <button type="submit" class="agree-del" name="delete">OK</button>
                </form>
            </div>
          </div>
        </div>
    </div>
</div>
<script>
    function openSide(){
        const sidebar = document.getElementById("sidebar");
        sidebar.classList.add("sidebar-active") ;

        window.addEventListener("mouseup", function(event) {
            if (event.target != sidebar) {
                sidebar.classList.remove("sidebar-active");
            }
        });

        window.addEventListener("resize", () =>{
            if(window.innerWidth > 414){
                sidebar.classList.add("sidebar-active") ;
            }
        });
    }
</script>

</body>
</html>