<?php

namespace View\Login;
session_start();

?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="./css/Login.css">
    <title>Document</title>
</head>
<body>

<div class = "container">
    <form action="" method="POST" class="form">
        <legend class="form-label">Đăng nhập</legend>

        <div class="form-group">
            <label for="" class="form-group_label">Số điện thoại:</label></br>
            <input type="text" class="form-control" name="phone" placeholder="Phone">
        </div>

        <div class="form-group">
            <label for="" class="form-group_label">Mật khẩu:</label></br>
            <input type="password" class="form-control" name="password" placeholder="password">
            <span class="error">
                <?php
                if(isset($_SESSION["err"])){
                    echo "*".$_SESSION["err"];
                    unset($_SESSION['err']);
                }
                ?>
            </span>
        </div>

        <div class="form-submit">
            <input type="submit" class="btn-submit" name="dangnhap" value="Đăng nhập">
        </div>
    </form>

</div>
</body>
</html>
