<?php

namespace View\Table;
use Controller\TableController;

session_start();
if(isset($_SESSION["staff"])){
    $staff = $_SESSION["staff"];
//    var_dump($staff);
}else{
    header('Location: Login.php');
}
$tableController = new TableController();
$tables = $tableController->getAllTable();
//var_dump($tables);
$table_id = 1;
if(isset($_GET['table_id'])){
    $_SESSION['table_id'] = $_GET['table_id'];
    $table_id = $_SESSION['table_id'];
}
$currenttable = $tableController->getTableById($table_id);
$grouptable = $tableController->getTableByOtherTable($table_id);

$tableCustomer = $tableController->getTableCustomerReserve();

?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="./css/style.css">
    <link rel="stylesheet" href="./css/Table.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <title>Document</title>
</head>
<body>

<div class = "page">
    <header class="header-wrapper">
        <div class="header-group">
            <button class="btn-open-sidebar" onclick="openSide()">☰</button>
            <label> Tên nhà hàng</label>
        </div>

        <div class="header-group" onclick="handleClickOnUser()">
            <i class='fa-solid fa-user icon-user'></i>
            <span class="header-identity">
                <?php echo $staff[0]['name'];?>
                <div class="user-info" id="user-info">
                    <p><a href="./ChangePasswordForm.php">Doi mat khau</a></p>
                    <p><a href="./index.php">Dang xuat</a></p>
                </div>
            </span>
        </div>
    </header>

    <div id="container" class="container">
        <aside id="sidebar" class="sidebar-wrapper">
            <label>Danh mục quản lý</label>
            <a href="#" class="sidebar-link active">
                <i class="fa-solid fa-table"></i>
                Quản lý Bàn
            </a>
            <a href="./Bill.php" class="sidebar-link">
                <i class="fa-solid fa-money-bill"></i>
                Quản lý Hóa đơn
            </a>
            <a href="Dish.php" class="sidebar-link">
                <i class="fa-solid fa-utensils"></i>
                Quản lý Món ăn
            </a>
            <a href="Event.php" class="sidebar-link">
                <i class="fa-solid fa-calendar-check"></i>
                Quản lý Sự kiện
            </a>
            <a href="Report.php" class="sidebar-link">
                <i class="fa-solid fa-chart-column"></i>
                Thống kê kinh doanh
            </a>
        </aside>

        <content id="content-wrapper" class="content-wrapper">
            <nav class="content-nav">
                <a href="
                <?php
                $reserve_table_url = $_SERVER['PHP_SELF'];
                $reserve_table_url .= "?reserve";
                echo $reserve_table_url;
                ?>"
                   class="reserve-url"
                >
                    Đặt bàn
                </a>

                <a href="
                <?php
                $add_table_url = $_SERVER['PHP_SELF'];
                $add_table_url .= "?add_table";
                echo $add_table_url;
                ?>"
                   class="add-table-url"
                >
                    Thêm bàn
                </a>

                <a href="
                <?php
                $deleta_table_url = $_SERVER['PHP_SELF'];
                $deleta_table_url .= "?delete_table";
                echo $deleta_table_url;
                ?>"
                   class="delete-table-url"
                >
                    Xóa bàn
                </a>
            </nav>
            <div class="table-wrapper">
<!--------------------------table-list-start-------------------------->
                <div class="content-table">
                    <?php if ($tableCustomer != null && isset($_GET['reserve'])) :?>
                        <div class='list-table-customer'>
                            <label class="list-table-customer-notification">* Bàn khách vừa đặt</label>
                            <?php
                            foreach ($tableCustomer as $table){
                                echo "<div class='table-customer-group'>";

                                echo "<div class='table-customer-label dropdown'>";
                                echo "<span>";
                                echo $table['customer_name']." - ".$table['phone'];
                                echo "</span>";
                                echo "<i class='fa-solid fa-angle-down'></i>";
                                echo "</div>";

                                echo "<div class='table-customer-content'>";

                                echo "<div class='table-customer-content-group'>";
                                echo "<label>";
                                echo "Tên khách hàng:";
                                echo "</label>";
                                echo "<span>";
                                echo $table['customer_name'];
                                echo "</span>";
                                echo "</div>";

                                echo "<div class='table-customer-content-group'>";
                                echo "<label>";
                                echo "SĐT:";
                                echo "</label>";
                                echo "<span>";
                                echo $table['phone'];
                                echo "</span>";
                                echo "</div>";

                                echo "<div class='table-customer-content-group'>";
                                echo "<label>";
                                echo "Số người:";
                                echo "</label>";
                                echo "<span>";
                                echo $table['number_people'];
                                echo "</span>";
                                echo "</div>";

                                echo "<div class='table-customer-content-group'>";
                                echo "<label>";
                                echo "Thời gian đặt:";
                                echo "</label>";
                                echo "<span>";
                                echo $table['time_reserve'];
                                echo "</span>";
                                echo "</div>";

                                echo "<form method='post'>";
                                $table_customer_reserve_id = $table['table_customer_reserve_id'];
                                echo "<input type='hidden' name='table_customer_reserve_id' value='$table_customer_reserve_id' >";
                                echo "<button type='submit' name='delete_table_customer_reserve' class='btn-delete_table_customer_reserve'>";
                                echo "Xác nhận";
                                echo "</button>";
                                echo "</form>";

                                echo "</div>";

                                echo " </div>";
                            }
                            ?>
                        </div>
                    <?php endif;?>
                    <div class="table-list">
                        <div class="table-note">
                            <div class="table-note-group">
                                <button class="table-not-booked"></button>
                                <span>Chưa đặt</span>
                            </div>
                            <div class="table-note-group">
                                <button class="table-booked"></button>
                                <span>Đã đặt</span>
                            </div>
                            <div class="table-note-group">
                                <button class="table-received"></button>
                                <span>Đang sử dụng</span>
                            </div>
                        </div>
                        <div class="table-list-content">
                            <?php
                            foreach ($tables as $table){
                                $tableurl = $_SERVER['PHP_SELF'];
                                $tableurl .= "?table_id=".$table['table_id'];
                                if($table['status'] == 0){
                                    echo "<a class='table-not-booked' href ='$tableurl'>";
                                    echo "<span>";
                                    echo $table['number'];
                                    echo "</span>";
                                    echo "</a>";
                                }elseif ($table['status'] == 1){
                                    echo "<a class='table-booked' href ='$tableurl'>";
                                    echo "<span>";
                                    echo $table['number'];
                                    echo "</span>";
                                    echo "</a>";
                                }else{
                                    echo "<a class='table-received' href ='$tableurl'>";
                                    echo "<span>";
                                    echo $table['number'];
                                    echo "</span>";
                                    echo "</a>";
                                }
                            }
                            ?>
                        </div>
                    </div>

                </div>
                <!--------------------------table-list-end-------------------------->

                <?php if (isset($_GET['add_table'])):?>
                    <!-----------------------------------form-add-table-start------------------->
                    <form method="post" action="" class="form-add-table">
                        <label class="form-add-table-label">Thông tin bàn</label>
                        <div class="form-add-table-group">
                            <label>Số bàn:</label>
                            <input type="text" name="number" required>
                        </div>
                        <span class="error">
                        <?php
                        if(isset($_SESSION["err"])){
                            echo "*".$_SESSION["err"];
                            unset($_SESSION['err']);
                        }
                        ?>
                        </span>
                        <div class="group-btn">
                            <button type="submit" class="btn-add-table" name="add_table">Thêm bàn</button>
                            <button type="reset" class="btn-cancel">Hủy bỏ</button>
                        </div>
                    </form>
                    <!-----------------------------------form-add-table-start------------------->
                <?php elseif (isset($_GET['delete_table'])):?>
                    <!-----------------------------------form-delete-table-start------------------->
                    <form method="post" action="" class="form-delete-table">
                        <label class="form-delete-table-label">Chọn bàn muốn xóa</label>
                        <div class="form-checkbox">
                            <?php
                            foreach ($tables as $table){
                                $id = $table['table_id'];
                                echo "<div class='form-checkbox-input'>";
                                echo "<input type='checkbox' name='$id' value='$id' >";
                                echo "<span>";
                                echo $table['number'];
                                echo "</span>";
                                echo "</div>";
                            }
                            ?>
                        </div>
                        <span class="error">
                        <?php
                        if(isset($_SESSION["err"])){
                            echo "*".$_SESSION["err"];
                            unset($_SESSION['err']);
                        }
                        ?>
                        </span>
                        <div class="group-btn">
                            <button type="submit" class="btn-delete-table" name="delete_table">Xóa bàn</button>
                        </div>
                    </form>
                    <!-----------------------------------form-delete-table-start------------------->

                <?php elseif(isset($_GET['reserve'])):?>
                    <!-----------------------------------form-reserve-start------------------->
                    <form method="post" action="" class="form-reserve">
                        <label class="form-reserve-label">Thông tin đặt bàn</label>
                        <div class="form-reserve-group">
                            <label>Tên khách hàng:</label>
                            <input type="text" name="customer_name" required>
                        </div>
                        <div class="form-reserve-group">
                            <label>Số điện thoại:</label>
                            <input type="text" name="phone" required>
                        </div>
                        <div class="form-reserve-group">
                            <label>Số người:</label>
                            <input type="text" name="number_people" required>
                        </div>
                        <div class="form-reserve-group">
                            <label>Thời gian đặt:</label>
                            <input type="datetime-local" name="time_reserve" required>
                        </div>
                        <div class="form-reserve-checkbox">
                            <label>Danh sách bàn:</label>
                            <div class="form-checkbox">
                            <?php
                            foreach ($tables as $table){
                                if($table['status'] == 0){
                                    $id = $table['table_id'];
                                    echo "<div class='form-checkbox-input'>";
                                    echo "<input type='checkbox' name='$id' value='$id' >";
                                    echo "<span>";
                                    echo $table['number'];
                                    echo "</span>";
                                    echo "</div>";
                                }
                            }
                            ?>
                            </div>
                        </div>
                        <div class="group-btn">
                            <button type="submit" class="btn-reserve" name="reserve_table">Đặt bàn</button>
                            <button type="reset" class="btn-cancel">Hủy bỏ</button>
                        </div>
                    </form>
                    <!-----------------------------------form-reserve-end------------------->

                <?php else:?>
<!----------------------table-detail--------------------->
                <div id="table-detail" class="table-detail">
                    <label class="detail-label">
                        Bàn số
                        <?php echo $currenttable[0]['number']?>
                    </label>
                    <div class="table-detail-group">
                        <label class="infor-label">Bàn số: </label>
                        <span> <?php echo $currenttable[0]['number']?></span>
                    </div>
                    <?php if($currenttable[0]['status'] == 0):?>
                        <!-----------------------table-not-booked-detail-start----------------------->
                        <div class="table-detail-group">
                            <label class="infor-label">Trạng thái: </label>
                            <span>Chưa đặt</span>
                        </div>
                        <!-----------------------table-not-booked-detail-end----------------------->

                    <?php elseif ($currenttable[0]['status'] == 1):?>
                    <!-----------------------table-booked-detail-start----------------------->
                        <div class="table-detail-group">
                            <label class="infor-label">Trạng thái: </label>
                            <span>Đã đặt</span>
                        </div>
                        <div class="table-detail-group">
                            <label class="infor-label">Tên khách hàng: </label>
                            <span> <?php echo $currenttable[0]['customer_name']?></span>
                        </div>
                        <div class="table-detail-group">
                            <label class="infor-label">Số điện thoại: </label>
                            <span> <?php echo $currenttable[0]['phone']?></span>
                        </div>
                        <div class="table-detail-group">
                            <label class="infor-label">Số người: </label>
                            <span> <?php echo $currenttable[0]['number_people']?></span>
                        </div>
                        <div class="table-detail-group">
                            <label class="infor-label">Thời gian đặt: </label>
                            <span> <?php echo $currenttable[0]['time_reserve']?></span>
                        </div>
                        <div class="table-detail-group">
                            <label class="infor-label">Các bàn đặt cùng: </label>
                            <span>
                                <?php
                                $numgrouptable = count($grouptable);
                                foreach ($grouptable as $key => $table){
                                    if($key == $numgrouptable-1){
                                        echo $table['number'].".";
                                    }else{
                                        echo $table['number'].", ";
                                    }
                                }
                                ?>
                            </span>
                        </div>
                        <div class="group-btn">
                            <button id="btn-update-reserve" class="btn-update-reserve">Chỉnh sửa thông tin</button>
                            <button id="btn-cancel-reserve" class="btn-cancel-reserve">Hủy đặt bàn</button>
                        </div>
                        <!-----------------------table-booked-detail-end----------------------->
                    <?php elseif ($currenttable[0]['status'] == 2): ?>
                    <!-----------------------table-received-detail-start----------------------->
                        <div class="table-detail-group">
                            <label class="infor-label">Trạng thái: </label>
                            <span>Đang sử dụng</span>
                        </div>
                        <div class="table-detail-group">
                            <label class="infor-label">Tên khách hàng: </label>
                            <span> <?php echo $currenttable[0]['customer_name']?></span>
                        </div>
                        <div class="table-detail-group">
                            <label class="infor-label">Số điện thoại: </label>
                            <span> <?php echo $currenttable[0]['phone']?></span>
                        </div>
                        <div class="table-detail-group">
                            <label class="infor-label">Số người: </label>
                            <span> <?php echo $currenttable[0]['number_people']?></span>
                        </div>
                        <div class="table-detail-group">
                            <label class="infor-label">Thời gian đặt: </label>
                            <span> <?php echo $currenttable[0]['time_reserve']?></span>
                        </div>
                        <div class="table-detail-group">
                            <label class="infor-label">Các bàn đặt cùng: </label>
                            <span>
                                <?php
                                $numgrouptable = count($grouptable);
                                foreach ($grouptable as $key => $table){
                                    if($key == $numgrouptable-1){
                                        echo $table['number'].".";
                                    }else{
                                        echo $table['number'].", ";
                                    }
                                }
                                ?>
                            </span>
                        </div>
                    <!-----------------------table-received-detail-end----------------------->

                    <?php endif;?>
                </div>

<!-----------------------table-booked-update-start----------------------->
                <form id="form-update-reserve" class="form-update-reserve" method="post" action="">
                    <label class="detail-label">
                        Bàn số
                        <?php echo $currenttable[0]['number']?>
                    </label>
                    <input type="hidden" name="table_id" value="<?php echo $currenttable[0]['table_id']?>">

                    <div class="form-reserve-group">
                        <label>Trạng thái: </label>
                        <div class="form-reserve-radio">
                            <input class="input-radio" type="radio" name="status" value="1" checked>
                            <label>Đã đặt</label>
                            <input class="input-radio" type="radio" name="status" value="2">
                            <label>Đang sử dụng</label>
                        </div>
                    </div>
                    <div class="form-reserve-group">
                        <label>Tên khách hàng: </label>
                        <input type="text" name="customer_name" value="<?php echo $currenttable[0]['customer_name']?>">
                    </div>
                    <div class="form-reserve-group">
                        <label>Số điện thoại: </label>
                        <input type="text" name="phone" value="<?php echo $currenttable[0]['phone']?>">
                    </div>
                    <div class="form-reserve-group">
                        <label>Số người: </label>
                        <input type="number" name="number_people" value="<?php echo $currenttable[0]['number_people']?>">
                    </div>
                    <div class="form-reserve-group">
                        <label>Thời gian đặt: </label>
                        <input type="datetime-local" name="time_reserve" value="<?php echo $currenttable[0]['time_reserve']?>">
                    </div>
                    <div class="form-reserve-checkbox">
                        <label>Các bàn đặt cùng: </label>
                        <div class="form-checkbox">
                            <?php
                            foreach ($tables as $table){
                                $id = $table['table_id'];
                                $booked = 0;
                                foreach ($grouptable as $tablereserve){
                                    if($id == $tablereserve['table_id']){
                                        $booked = 1;
                                        break;
                                    }
                                }
                                if($table['status'] == 0 || $table['status'] == 1){
                                    if ($booked) {
                                        echo "<div class='form-checkbox-input'>";
                                        echo "<input type='checkbox' name='$id' value='$id' checked>";
                                        echo "<span>";
                                        echo $table['number'];
                                        echo "</span>";
                                        echo "</div>";
                                    } else {
                                        echo "<div class='form-checkbox-input'>";
                                        echo "<input type='checkbox' name='$id' value='$id' >";
                                        echo "<span>";
                                        echo $table['number'];
                                        echo "</span>";
                                        echo "</div>";
                                    }
                                }
                            }
                            ?>
                        </div>
                    </div>
                    <div class="group-btn">
                        <button type="submit" name="update-reserve" class="btn-update">Xác nhận chỉnh sửa</button>
                        <button type="reset" id = "btn-cancel-update" class="btn-cancel">Hủy cập nhật</button>
                    </div>
                </form>
       <!-----------------------table-booked-update-end----------------------->

                <?php endif;?>
            </div>
            
        </content>
    </div>
</div>

<script>
    function handleClickOnUser() {
        const user = document.getElementById('user-info');
        if (user.style.display == "none") {
            user.style.display = "block";
            document.getElementById('container').style.opacity = 0.3;
            return;
        }
        user.style.display = "none";
        document.getElementById('container').style.opacity = 1;
    }
</script>
<!------------------------popup-confirm-start------------------------>

<div id="popup-confirm-reserve" class="popup-confirm-reserve">
    <form class="form-confirm-reserve" method="post" action="">
        <div class="form-confirm-reserve-label">Xác nhận hủy toàn bộ bàn liên quan tới khách hàng</div>
        <input type="hidden" name="cancel-reserve-all" value="<?php echo $currenttable[0]['table_id'];?>">
        <div class="btn-confirm-group">
            <button type="submit" class="btn-confirm-reserve-cancel">Xác nhận</button>
            <button type="reset" id="btn-cancel-confirm-reserve" class="btn-cancel">Hủy bỏ</button>
        </div>
    </form>
</div>

<!----------------------popup-confirm-end---------------------->

<script>
    function openSide(){
        const sidebar = document.getElementById("sidebar");
        sidebar.classList.add("sidebar-active") ;

        window.addEventListener("mouseup", function(event) {
            if (event.target != sidebar) {
                sidebar.classList.remove("sidebar-active");
            }
        });

        window.addEventListener("resize", () =>{
            if(window.innerWidth > 414){
                sidebar.classList.add("sidebar-active") ;
            }
        });
    }
</script>
<script>
    var dropdown = document.getElementsByClassName("dropdown");
    var i;

    for (i = 0; i < dropdown.length; i++) {
        dropdown[i].addEventListener("click", function() {
            var dropdownContent = this.nextElementSibling;
            if (dropdownContent.style.display === "block") {
                dropdownContent.style.display = "none";
            } else {
                dropdownContent.style.display = "block";
            }
        });
    }
</script>
<script>
    const btn_update_reserve = document.getElementById("btn-update-reserve");
    const btn_cancel_reserve = document.getElementById("btn-cancel-reserve");
    const form_update_reserve = document.getElementById("form-update-reserve");
    const table_detail = document.getElementById("table-detail");
    const btn_cancel_update = document.getElementById("btn-cancel-update");
    const popup_confirm_reserve = document.getElementById("popup-confirm-reserve");
    const btn_cancel_confirm_reserve = document.getElementById("btn-cancel-confirm-reserve");
    if(btn_update_reserve != null){
        btn_update_reserve.onclick = function () {
            table_detail.style.display = "none";
            form_update_reserve.style.display = "block";
        }
    }
    if (btn_cancel_update != null){
        btn_cancel_update.onclick = function () {
            table_detail.style.display = "block";
            form_update_reserve.style.display = "none";
        }
    }
    if (btn_cancel_reserve != null){
        btn_cancel_reserve.onclick = function () {
            popup_confirm_reserve.style.display = "block";
        }
    }
    if (btn_cancel_confirm_reserve != null){
        btn_cancel_confirm_reserve.onclick = function () {
            popup_confirm_reserve.style.display = "none";
        }
    }
</script>
</body>
</html>
