<?php

namespace View\Table;
session_start();
if(isset($_SESSION["staff"])){
    $staff = $_SESSION["staff"];
}else{
    header('Location: Login.php');
}

?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="./css/Login.css">
    <title>Document</title>
</head>
<body>

<div class = "container">
    <div>
        <?php
        echo $staff[0]['name'];
        ?>
    </div>
Table
</div>
</body>
</html>
