<?php

namespace View\Dish;
use Controller\DishController;
// use Model;
use Model\Dish\DishModel;
session_start();
if(isset($_SESSION["staff"])){
    $staff = $_SESSION["staff"];
//    var_dump($staff);
}else{
    header('Location: index.php');
}
    // include('/xampp/htdocs/WebTechEServices/WebTech_Project/CN_Web/Admin/Model/Dish/DishModel.php');
    $dish_1 = new DishModel(
        '001', 
        'mon_chinh', 
        'Beaf Steak thịt bò Kobe Phiên bản Mỹ Đình',
        'Ba chỉ bò Mỹ là thịt ba chỉ của con bò ở Mỹ',
        '169000',
        'https://cdn.shopify.com/s/files/1/2128/4095/products/Beef-Sirlion1_d64f721b-db11-4adf-ab7f-69c7d534fb4d_600x.jpg?v=1581030208'
    );
?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="./css/style.css">
    <link rel="stylesheet" href="./css/Dish.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <title>Dish Edit</title>
</head>
<body>

<div class = "page">
    <header class="header-wrapper">
        <div class="header-group">
            <button class="btn-open-sidebar" onclick="openSide()">☰</button>
            <label> Tên nhà hàng</label>
        </div>

        <div class="header-group">
            <i class='fa-solid fa-user icon-user'></i>
            <span class="header-identity">
                <?php echo $staff[0]['name'];?>
            </span>
        </div>
    </header>
    <div class="container">
        <aside id="sidebar" class="sidebar-wrapper">
            <label>Danh mục quản lý</label>
            <a href="Table.php" class="sidebar-link">
                <i class="fa-solid fa-table"></i>
                Quản lý Bàn
            </a>
            <a href="#" class="sidebar-link">
                <i class="fa-solid fa-money-bill"></i>
                Quản lý Hóa đơn
            </a>
            <a href="" class="sidebar-link active">
                <i class="fa-solid fa-utensils"></i>
                Quản lý Món ăn
            </a>
            <a href="Event.php" class="sidebar-link">
                <i class="fa-solid fa-calendar-check"></i>
                Quản lý Sự kiện
            </a>
            <a href="Report.php" class="sidebar-link">
                <i class="fa-solid fa-chart-column"></i>
                Thống kê kinh doanh
            </a>
        </aside>

        <content class="content-wrapper">
            <nav class="content-nav-detail">
                <form method="GET" action="./Dish.php">
                    <button name="button_return" type="submit" class="dish-button dish-button-return">
                        Trở lại              
                    </button>
                </form>
                
                <div class="dish-add-title">Chỉnh sửa thông tin món ăn</div>
                <!-- <a href="#" class="dish-button dish-button-add">
                    <i class="fa-regular fa-square-plus"></i>
                    Thêm món ăn              
                </a> -->
            </nav>
            
            <div class="dish-add-container">
                <form class="dish-add-form">
                    <div class="add-form-wrap">
                        <div class="add-form-item">
                            <label for="dish-category" class="form-label">Loại món ăn</label>
                            </>
                                <input disabled class="edit-category" value="mon_chinh" list="categories_list" type="text" class="form-control" id="dish-category" name="dish-category">
                                <datalist id="categories_list">
                                    <option value="khai_vi">Món khai vị</option>
                                    <option value="mon_chinh">Món chính</option>
                                    <option value="trang_mieng">Món tráng miệng</option>
                                </datalist>
                            </>
                        </div>
                        <div class="add-form-item">
                            <label for="dish-name" class="form-label">Tên</label>
                            <input type="text" id="dish-name" name="dish-name">
                        </div>
                        <div class="add-form-item">
                            <label for="dish-description" class="form-label">Mô tả</label>
                            <textarea rows="5" type="text" id="dish-description" name="dish-description"></textarea>
                        </div>
                        <div class="add-form-item">
                            <label for="dish-image" class="form-label">Url Hình ảnh</label>
                            <input type="text" id="dish-image" name="dish-image">
                        </div>  
                    </div>
                    <div class="confirm-add-wrap">
                        <button class="button-edit-submit" type="submit">Xác Nhận Chỉnh sửa</button>
                    </div>
                </form>
                
            </div>
            
        </content>
    </div>
</div>
<script>
    function openSide(){
        const sidebar = document.getElementById("sidebar");
        sidebar.classList.add("sidebar-active") ;

        window.addEventListener("mouseup", function(event) {
            if (event.target != sidebar) {
                sidebar.classList.remove("sidebar-active");
            }
        });

        window.addEventListener("resize", () =>{
            if(window.innerWidth > 414){
                sidebar.classList.add("sidebar-active") ;
            }
        });
    }
</script>

</body>
</html>
