<?php

namespace View\Dish;

use Controller;
use Controller\DishController;

session_start();
if(isset($_SESSION["staff"])){
    $staff = $_SESSION["staff"];
//    var_dump($staff);
}else{
    header('Location: Login.php');
}
    $dishController = new DishController();

    function test_input($data) {
        $data = trim($data);
        $data = stripslashes($data);
        $data = htmlspecialchars($data);
        return $data;
    }


    $categoryErr = $nameErr = $priceErr = $descriptionErr = $imageUrlErr = "";
    $category = $name = $price = $description = $image_url = "";
    $add_success = false;
    $fileRedirect = htmlspecialchars($_SERVER['PHP_SELF']);

    if ($_SERVER["REQUEST_METHOD"] == "POST") {
        if (empty($_POST["dish-category"])) {
            $categoryErr = "Bạn phải chọn Loại món ăn!";
        } else {
            $category = test_input($_POST['dish-category']);
        }

        if (empty($_POST["dish-name"])) {
            $nameErr = "Bạn phải điền Tên!";
        } else {
            $name = test_input($_POST['dish-name']);
        }

        if (empty($_POST["dish-price"])) {
            $priceErr = "Bạn phải điền Giá tiền!";
        } else {
            $price = test_input($_POST['dish-price']);
            if (!is_numeric($price)) {
                $priceErr = "Định dạng giá tiền Không hợp lệ!";
            }
        }

        if (empty($_POST["dish-description"])) {
            $descriptionErr = "Bạn phải điền Mô tả!";
        } else {
            $description = test_input($_POST['dish-description']);
        }

        if (empty($_POST["dish-image"])) {
            $imageUrlErr = "Bạn phải điền Link Url ảnh!";
        } else {
            $image_url = test_input($_POST['dish-image']);
            if (!preg_match("/\b(?:(?:https?|ftp):\/\/|www\.)[-a-z0-9+&@#\/%?=~_|!:,.;]*[-a-z0-9+&@#\/%=~_|]/i",$image_url)) {
                $imageUrlErr = "Link Url không hợp lệ!";
            }
        }

        if (isset($_POST['button_add_confirm'])) {
            if (!$imageUrlErr && !$descriptionErr && !$nameErr && !$categoryErr && !$priceErr) {
                // $dishController->insertDish($category, $name, $description, $price, $image_url);
                $fileRedirect = 'Dish.php';

                $category = $name = $price = $description = $image_url = "";
                $add_success = true;
            } else {
                $fileRedirect = htmlspecialchars($_SERVER["PHP_SELF"]);
            }
        }
    }
?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="./css/style.css">
    <link rel="stylesheet" href="./css/Dish.css">
    <link rel="stylesheet" href="./css/Dish_responsive.css">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <title>Dish add</title>
</head>
<body>

<div class = "page">
    <header class="header-wrapper">
        <div class="header-group">
            <button class="btn-open-sidebar" onclick="openSide()">☰</button>
            <label>BABA RESTO</label>
        </div>

        <div class="header-group" onclick="handleClickOnUser()">
            <i class='fa-solid fa-user icon-user'></i>
            <span class="header-identity">
                <?php echo $staff[0]['name'];?>
                <div class="user-info" id="user-info">
                    <p><a href="./ChangePasswordForm.php">Đổi mật khẩu</a></p>
                    <p><a href="./index.php">Đăng xuất</a></p>
                </div>
            </span>
        </div>
    </header>
    <div class="container">
        <aside id="sidebar" class="sidebar-wrapper">
            <label>Danh mục quản lý</label>
            <a href="Table.php" class="sidebar-link">
                <i class="fa-solid fa-table"></i>
                Quản lý Bàn
            </a>
            <a href="Bill.php" class="sidebar-link">
                <i class="fa-solid fa-money-bill"></i>
                Quản lý Hóa đơn
            </a>
            <a href="" class="sidebar-link active">
                <i class="fa-solid fa-utensils"></i>
                Quản lý Món ăn
            </a>
            <a href="Event.php" class="sidebar-link">
                <i class="fa-solid fa-calendar-check"></i>
                Quản lý Sự kiện
            </a>
            <a href="Report.php" class="sidebar-link">
                <i class="fa-solid fa-chart-column"></i>
                Thống kê kinh doanh
            </a>
        </aside>

        <content class="content-wrapper">
            <nav class="content-nav-detail">
                <form method="GET" action="./Dish.php">
                    <button name="button_return" type="submit" class="dish-button dish-button-return">
                        Trở lại              
                    </button>
                </form>
                
                <div class="dish-add-title">Thêm món ăn</div>
                <!-- <a href="#" class="dish-button dish-button-add">
                    <i class="fa-regular fa-square-plus"></i>
                    Thêm món ăn              
                </a> -->
            </nav>
            
            <div class="dish-add-container">
                <form class="dish-add-form" action="<?php echo $fileRedirect?>" method="POST">
                    <div class="add-form-wrap">
                        <?php echo $add_success ? "<div class='add-success'>Bạn đã thêm món ăn thành công</div>" : "" ?>
                        <div class="add-form-item">
                            <label for="dish-category" class="form-label">Loại món ăn</label>
                            </>
                                <input list="categories_list" type="text" class="form-control" id="dish-category" name="dish-category" value="<?php echo $category ?>">
                                <datalist id="categories_list">
                                    <option value="khai_vi">Món khai vị</option>
                                    <option value="mon_chinh">Món chính</option>
                                    <option value="trang_mieng">Món tráng miệng</option>
                                </datalist>
                                <?php echo !empty($categoryErr) ? "<p class='error'>* $categoryErr</p>" : "" ?>

                            </>
                        </div>
                        <div class="add-form-item">
                            <label for="dish-name" class="form-label">Tên</label>
                            <input type="text" id="dish-name" name="dish-name" value="<?php echo $name?>">
                            <!-- <p class="error">* Lỗi nhập</p> -->
                            <?php echo !empty($nameErr) ? "<p class='error'>* $nameErr</p>" : "" ?>
                        </div>

                        <div class="add-form-item">
                            <label for="dish-name" class="form-label">Giá</label>
                            <input type="text" id="dish-price" name="dish-price" value="<?php echo $price?>">
                            <!-- <p class="error">* Lỗi nhập</p> -->
                            <?php echo !empty($priceErr) ? "<p class='error'>* $priceErr</p>" : "" ?>
                        </div>
                        
                        <div class="add-form-item">
                            <label for="dish-description" class="form-label">Mô tả</label>
                            <textarea rows="5" type="text" id="dish-description" name="dish-description"><?php echo $description?></textarea>
                            <?php echo !empty($descriptionErr) ? "<p class='error'>* $descriptionErr</p>" : "" ?>
                        </div>
                        <div class="add-form-item">
                            <label for="dish-image" class="form-label">Url Hình ảnh</label>
                            <input type="text" id="dish-image" name="dish-image" value="<?php echo $image_url?>">
                            <?php echo !empty($imageUrlErr) ? "<p class='error'>* $imageUrlErr</p>" : "" ?>
                        </div>  
                    </div>
                    <div class="confirm-add-wrap">
                        <button class="button-add-submit" type="submit" name="button_add_confirm">Xác Nhận Thêm</button>
                    </div>
                </form>
                
            </div>
            
        </content>
    </div>
</div>

<script>
    function openSide(){
        const sidebar = document.getElementById("sidebar");
        sidebar.classList.add("sidebar-active") ;

        window.addEventListener("mouseup", function(event) {
            if (event.target != sidebar) {
                sidebar.classList.remove("sidebar-active");
            }
        });

        window.addEventListener("resize", () =>{
            if(window.innerWidth > 414){
                sidebar.classList.add("sidebar-active") ;
            }
        });
    }

    function handleClickOnUser() {
        const user = document.getElementById('user-info');
        if (user.style.display == "none") {
            user.style.display = "block";
            document.getElementById('container').style.opacity = 0.3;
            return;
        }
        user.style.display = "none";
        document.getElementById('container').style.opacity = 1;
    }
</script>

</body>
</html>
