<?php

namespace View\Dish;
use Controller\DishController;
use Model;
use Model\Dish\DishModel;
session_start();
if(isset($_SESSION["staff"])){
    $staff = $_SESSION["staff"];
//    var_dump($staff);
}else{
    header('Location: Login.php');
}
// include 'C:/xampp/WebTechEServices/WebTech_Project/CN_Web/Admin/Model/Dish/DishModel.php';

// session_start();
// if(isset($_SESSION["staff"])){
//     $staff = $_SESSION["staff"];
// //    var_dump($staff);
// } else{
//     header('Location: index.php');
// }
// $tableController = new TableController();
// $tables = $tableController->getAllTable();
// //var_dump($tables);
// $table_id = 1;
// if(isset($_GET['table_id'])){
//     $_SESSION['table_id'] = $_GET['table_id'];
//     $table_id = $_SESSION['table_id'];
// }
// $currenttable = $tableController->getTableById($table_id);
// $grouptable = $tableController->getTableByOtherTable($table_id);
?>

<?php 
    // include('/xampp/htdocs/WebTechEServices/WebTech_Project/CN_Web/Admin/Model/Dish/DishModel.php');

    $dish_1 = new DishModel(
        '001', 
        'mon_chinh', 
        'Beaf Steak thịt bò Kobe Phiên bản Mỹ Đình',
        'Ba chỉ bò Mỹ là thịt ba chỉ của con bò ở Mỹ',
        '169000',
        'https://cdn.shopify.com/s/files/1/2128/4095/products/Beef-Sirlion1_d64f721b-db11-4adf-ab7f-69c7d534fb4d_600x.jpg?v=1581030208'
    );
?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="./css/style.css">
    <link rel="stylesheet" href="./css/Dish.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <title>Dishes Managament</title>
</head>
<body>

<div class = "page">
    <header class="header-wrapper">
        <div class="header-group">
            <button class="btn-open-sidebar" onclick="openSide()">☰</button>
            <label> Tên nhà hàng</label>
        </div>

        <div class="header-group">
            <i class='fa-solid fa-user icon-user'></i>
            <span class="header-identity">
                <?php echo $staff[0]['name'];?>
            </span>
        </div>
    </header>
    <div class="container">
        <aside id="sidebar" class="sidebar-wrapper">
            <label>Danh mục quản lý</label>
            <a href="Table.php" class="sidebar-link ">
                <i class="fa-solid fa-table"></i>
                Quản lý Bàn
            </a>
            <a href="#" class="sidebar-link">
                <i class="fa-solid fa-money-bill"></i>
                Quản lý Hóa đơn
            </a>
            <a href="#" class="sidebar-link active">
                <i class="fa-solid fa-utensils"></i>
                Quản lý Món ăn
            </a>
            <a href="Event.php" class="sidebar-link">
                <i class="fa-solid fa-calendar-check"></i>
                Quản lý Sự kiện
            </a>
            <a href="Report.php" class="sidebar-link">
                <i class="fa-solid fa-chart-column"></i>
                Thống kê kinh doanh
            </a>
        </aside>

        <content class="content-wrapper">
            <nav class="content-nav">
                <?php
                    // $reservetableurl = $_SERVER['PHP_SELF'];
                    // $reservetableurl .= "?reserve";
                    // echo "<a href='$reservetableurl' class='dish-button dish-button-return'>";
                    // echo "Trở lại";
                    // echo "</a>";
                ?>
                <a href="#" class="dish-button dish-button-return">
                    Trở lại              
                </a>
                <span class="dish-management-title">Danh sách món ăn</span>
                <form  action="./Dish.php" method="POST">
                    <button type="submit" name="add_button" class="dish-button dish-button-add"> 
                        <i class="fa-regular fa-square-plus"></i>
                        Thêm món ăn   
                    </button>  
                </form>
            </nav>
            <div class="content-main">
                <div class="search-filter-bar">
                    <div class="row">
                        <div class="search-bar">
                            <form class="search-form">
                                <input type="search" placeholder="search">
                                <button type="submit">
                                    <i class="fa-solid fa-magnifying-glass"></i>
                                </button>
                            </form>
                            
                        </div>
                        <div class="filter-list">
                            <div class="filter-bar">
                                <select class="form-select">
                                    <option>Tất cả</option>
                                    <option>Món khai vị</option>
                                    <option>Món chính</option>
                                    <option>Món tráng miệng</option>
                                </select>
                            </div>
                            <div class="filter-bar">
                                <select class="form-select">
                                    <option>Sắp xếp</option>
                                    <option>Đắt nhất</option>
                                    <option>Rẻ nhất</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="list-dish">
                    <div class="row list-dish-body">
                        <!-- 1 -->
                        <div class="dish-card-wrap">
                            <div class="dish-card-product">
                                <a class="dish-img-wrap" href="">
                                    <img src="<?php echo $dish_1->getImageUrl()?>">
                                </a>
                                <div class="dish-info-wrap">
                                    <a class="dish-title" title="<?php echo $dish_1->getName()?>" href="">
                                        <?php echo $dish_1->getName() ?>
                                    </a>
                                    <div class="dish-price">
                                        Giá: <?php echo $dish_1->getPrice() ?> <sup>vnđ</sup>
                                    </div>
                                    <div class="dish-category">
                                        <?php echo '#'.$dish_1->getCategory() ?>
                                    </div>
                                    <div class="row dish-list-action">
                                        <form title="Xem" action="Dish.php" method="GET">
                                            <button class="dish-view" name="button_view" type="submit">
                                                <i class="fa-solid fa-eye"></i>  
                                            </button>
                                        </form>
                                        <form  title="Sửa" action="Dish.php" method="POST">
                                            <button class="dish-edit" name="button_edit" type="submit">
                                                <i class="fa-solid fa-pen-to-square"></i>  
                                            </button>
                                        </form>
                                        <form  title="Xóa">
                                            <button class="dish-delete">
                                                <i class="fa-solid fa-eraser"></i>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- 2 -->
                        <div class="dish-card-wrap">
                            <div class="dish-card-product">
                                <a class="dish-img-wrap" href="">
                                    <img src="<?php echo $dish_1->getImageUrl()?>">
                                </a>
                                <div class="dish-info-wrap">
                                    <a class="dish-title" title="<?php echo $dish_1->getName()?>" href="">
                                        <?php echo $dish_1->getName() ?>
                                    </a>
                                    <div class="dish-price">
                                        Giá: <?php echo $dish_1->getPrice() ?> <sup>vnđ</sup>
                                    </div>
                                    <div class="row dish-list-action">
                                        <form title="Xem">
                                            <button class="dish-view" >
                                                <i class="fa-solid fa-eye"></i>  
                                            </button>
                                        </form>
                                        <form  title="Sửa">
                                            <button class="dish-edit">
                                                <i class="fa-solid fa-pen-to-square"></i>  
                                            </button>
                                        </form>
                                        <form  title="Xóa">
                                            <button class="dish-delete">
                                                <i class="fa-solid fa-eraser"></i>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- 3 -->
                        <div class="dish-card-wrap">
                            <div class="dish-card-product">
                                <a class="dish-img-wrap" href="">
                                    <img src="<?php echo $dish_1->getImageUrl()?>">
                                </a>
                                <div class="dish-info-wrap">
                                    <a class="dish-title" title="<?php echo $dish_1->getName()?>" href="">
                                        <?php echo $dish_1->getName() ?>
                                    </a>
                                    <div class="dish-price">
                                        Giá: <?php echo $dish_1->getPrice() ?> <sup>vnđ</sup>
                                    </div>
                                    <div class="row dish-list-action">
                                        <form title="Xem">
                                            <button class="dish-view" >
                                                <i class="fa-solid fa-eye"></i>  
                                            </button>
                                        </form>
                                        <form  title="Sửa">
                                            <button class="dish-edit">
                                                <i class="fa-solid fa-pen-to-square"></i>  
                                            </button>
                                        </form>
                                        <form  title="Xóa">
                                            <button class="dish-delete">
                                                <i class="fa-solid fa-eraser"></i>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- 4 -->
                        <div class="dish-card-wrap">
                            <div class="dish-card-product">
                                <a class="dish-img-wrap" href="">
                                    <img src="<?php echo $dish_1->getImageUrl()?>">
                                </a>
                                <div class="dish-info-wrap">
                                    <a class="dish-title" title="<?php echo $dish_1->getName()?>" href="">
                                        <?php echo $dish_1->getName() ?>
                                    </a>
                                    <div class="dish-price">
                                        Giá: <?php echo $dish_1->getPrice() ?> <sup>vnđ</sup>
                                    </div>
                                    <div class="row dish-list-action">
                                        <form title="Xem">
                                            <button class="dish-view" >
                                                <i class="fa-solid fa-eye"></i>  
                                            </button>
                                        </form>
                                        <form  title="Sửa">
                                            <button class="dish-edit">
                                                <i class="fa-solid fa-pen-to-square"></i>  
                                            </button>
                                        </form>
                                        <form  title="Xóa">
                                            <button class="dish-delete">
                                                <i class="fa-solid fa-eraser"></i>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- 5 -->
                        <div class="dish-card-wrap">
                            <div class="dish-card-product">
                                <a class="dish-img-wrap" href="">
                                    <img src="<?php echo $dish_1->getImageUrl()?>">
                                </a>
                                <div class="dish-info-wrap">
                                    <a class="dish-title" title="<?php echo $dish_1->getName()?>" href="">
                                        <?php echo $dish_1->getName() ?>
                                    </a>
                                    <div class="dish-price">
                                        Giá: <?php echo $dish_1->getPrice() ?> <sup>vnđ</sup>
                                    </div>
                                    <div class="row dish-list-action">
                                        <form title="Xem">
                                            <button class="dish-view" >
                                                <i class="fa-solid fa-eye"></i>  
                                            </button>
                                        </form>
                                        <form  title="Sửa">
                                            <button class="dish-edit">
                                                <i class="fa-solid fa-pen-to-square"></i>  
                                            </button>
                                        </form>
                                        <form  title="Xóa">
                                            <button class="dish-delete">
                                                <i class="fa-solid fa-eraser"></i>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="pagination">
                        <div class="pre-page">
                            Trang trước
                        </div>
                        <div class="list-page">
                            <ul>
                                <?php 
                                    echo "<li class='list-page-number number-active'>1</li>";
                                    for ($i = 2; $i <= 6; $i++)
                                        echo "<li class='list-page-number'>$i</li>"
                                ?>   
                            </ul>
                        </div>
                        <div class="pre-page">
                            Trang sau
                        </div>
                    </div>
                </div>
            </div>
            
        </content>
    </div>
</div>
<script>
    function openSide(){
        const sidebar = document.getElementById("sidebar");
        sidebar.classList.add("sidebar-active") ;

        window.addEventListener("mouseup", function(event) {
            if (event.target != sidebar) {
                sidebar.classList.remove("sidebar-active");
            }
        });

        window.addEventListener("resize", () =>{
            if(window.innerWidth > 414){
                sidebar.classList.add("sidebar-active") ;
            }
        });
    }
</script>

</body>
</html>
