<?php

namespace View\Dish;
use Controller\DishController;
// use Model;
// use Model\Dish\DishModel;

    $dishController = new DishController();
    function test_input($data) {
        $data = trim($data);
        $data = stripslashes($data);
        $data = htmlspecialchars($data);
        return $data;
    }

    if (isset($_GET['dish_id'])) {
        $dish_id = $_GET['dish_id'];
        // echo $dish_id;
        $dishDetail = $dishController->getDishById($dish_id);
        // echo  $dishDetail[0]['category'];
        $dishDetailInfo = $dishDetail[0];
    } else if (isset($_POST['dish_id'])) {
        $dish_id = $_POST['dish_id'];
        // echo $dish_id;
        $dishDetail = $dishController->getDishById($dish_id);
        // echo  $dishDetail[0]['category'];
        $dishDetailInfo = $dishDetail[0];
    }

    // echo $dishDetailInfo['name'];
    $categoryErr = $nameErr = $priceErr = $descriptionErr = $imageUrlErr = "";
    $category = $dishDetailInfo['category'];
    $name = $dishDetailInfo['name'];
    $description = $dishDetailInfo['description'];
    $price = $dishDetailInfo['price'];
    $image_url = $dishDetailInfo['image_url'];
    
    $error_nochange = false;
    $edit_success = false;

    $redirectFile = htmlspecialchars($_SERVER['PHP_SELF']);

    if ($_SERVER["REQUEST_METHOD"] == "POST") {
        if (empty($_POST["dish-category"])) {
            $categoryErr = "Bạn phải chọn Loại món ăn!";
        } else {
            $category = test_input($_POST['dish-category']);
        }

        if (empty($_POST["dish-name"])) {
            $nameErr = "Bạn phải điền Tên!";
        } else {
            $name = test_input($_POST['dish-name']);
        }

        if (empty($_POST["dish-price"])) {
            $priceErr = "Bạn phải điền Giá tiền!";
        } else {
            $price = test_input($_POST['dish-price']);
            if (!is_numeric($price)) {
                $priceErr = "Định dạng giá tiền Không hợp lệ!";
            }
        }

        if (empty($_POST["dish-description"])) {
            $descriptionErr = "Bạn phải điền Mô tả!";
        } else {
            $description = test_input($_POST['dish-description']);
        }

        if (empty($_POST["dish-image"])) {
            $imageUrlErr = "Bạn phải điền Link Url ảnh!";
        } else {
            $image_url = test_input($_POST['dish-image']);
            if (!preg_match("/\b(?:(?:https?|ftp):\/\/|www\.)[-a-z0-9+&@#\/%?=~_|!:,.;]*[-a-z0-9+&@#\/%=~_|]/i",$image_url)) {
                $imageUrlErr = "Link Url không hợp lệ!";
            }
        }

        if (isset($_POST['button_edit_confirm'])) {
            echo $dishDetailInfo['name'] . "==". $name;
            if (!$imageUrlErr && !$descriptionErr && !$nameErr && !$categoryErr && !$priceErr) {
                // if ($dishDetailInfo['name'] == $name && $dishDetailInfo['description'] == $description && $dishDetailInfo['price'] == $price && $dishDetailInfo['image_url'] == $image_url) {
                //     $edit_success = false;
                //     $error_nochange = true;
                //     $redirectFile = htmlspecialchars($_SERVER['PHP_SELF']);
                // } else {
                    // $dishController->updateDish($dish_id, $name, $description, $price, $image_url);
                    // $category = $name = $price = $description = $image_url = "";
                $redirectFile = "Dish.php";
                $edit_success = true;
                // }
                
            }
            else {
                $redirectFile = "Dish.php";
            }
        }
    }

?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="./css/style.css">
    <link rel="stylesheet" href="./css/Dish.css">
    <link rel="stylesheet" href="./css/Dish_responsive.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <title>Dish Edit</title>
</head>
<body>

<div class = "page">
    <header class="header-wrapper">
        <div class="header-group">
            <button class="btn-open-sidebar" onclick="openSide()">☰</button>
            <label> Tên nhà hàng</label>
        </div>

        <div class="header-group">
            <i class='fa-solid fa-user icon-user'></i>
            <span class="header-identity">
                <?php echo $staff[0]['name'];?>
            </span>
        </div>
    </header>
    <div class="container">
        <aside id="sidebar" class="sidebar-wrapper">
            <label>Danh mục quản lý</label>
            <a href="Table.php" class="sidebar-link">
                <i class="fa-solid fa-table"></i>
                Quản lý Bàn
            </a>
            <a href="#" class="sidebar-link">
                <i class="fa-solid fa-money-bill"></i>
                Quản lý Hóa đơn
            </a>
            <a href="" class="sidebar-link active">
                <i class="fa-solid fa-utensils"></i>
                Quản lý Món ăn
            </a>
            <a href="Event.php" class="sidebar-link">
                <i class="fa-solid fa-calendar-check"></i>
                Quản lý Sự kiện
            </a>
            <a href="Report.php" class="sidebar-link">
                <i class="fa-solid fa-chart-column"></i>
                Thống kê kinh doanh
            </a>
        </aside>

        <content class="content-wrapper">
            <nav class="content-nav-detail">
                <form method="GET" action="./Dish.php">
                    <button name="button_return" type="submit" class="dish-button dish-button-return">
                        Trở lại              
                    </button>
                </form>
                
                <div class="dish-add-title">Chỉnh sửa thông tin món ăn</div>
            </nav>
            <div class="dish-add-container">
                <form class="dish-add-form" action="<?php echo $redirectFile?>" method="POST">
                    <input style='display:none' type='number' name='dish_id' value=<?php echo $dish_id ?>>
                    <div class="add-form-wrap">
                    <?php echo $edit_success ? "<div class='add-success'>Bạn đã Chỉnh sửa thành công</div>" : "" ?>
                    
                        <div class="add-form-item">
                            <label for="dish-category" class="form-label">Loại món ăn</label>
                            </>
                                <input list="categories_list" type="text" class="edit-category" id="dish-category" name="dish-category" value="<?php echo $category ?>">
                                <datalist id="categories_list">
                                    <option value="khai_vi">Món khai vị</option>
                                    <option value="mon_chinh">Món chính</option>
                                    <option value="trang_mieng">Món tráng miệng</option>
                                </datalist>
                                <?php echo !empty($categoryErr) ? "<p class='error'>* $categoryErr</p>" : "" ?>

                            </>
                        </div>
                        <div class="add-form-item">
                            <label for="dish-name" class="form-label">Tên</label>
                            <input type="text" id="dish-name" name="dish-name" value="<?php echo $name?>">
                            <!-- <p class="error">* Lỗi nhập</p> -->
                            <?php echo !empty($nameErr) ? "<p class='error'>* $nameErr</p>" : "" ?>
                        </div>

                        <div class="add-form-item">
                            <label for="dish-name" class="form-label">Giá</label>
                            <input type="text" id="dish-price" name="dish-price" value="<?php echo $price?>">
                            <?php echo !empty($priceErr) ? "<p class='error'>* $priceErr</p>" : "" ?>
                        </div>
                        
                        <div class="add-form-item">
                            <label for="dish-description" class="form-label">Mô tả</label>
                            <textarea rows="5" type="text" id="dish-description" name="dish-description"><?php echo $description?></textarea>
                            <?php echo !empty($descriptionErr) ? "<p class='error'>* $descriptionErr</p>" : "" ?>
                        </div>
                        <div class="add-form-item">
                            <label for="dish-image" class="form-label">Url Hình ảnh</label>
                            <input type="text" id="dish-image" name="dish-image" value="<?php echo $image_url?>">
                            <?php echo !empty($imageUrlErr) ? "<p class='error'>* $imageUrlErr</p>" : "" ?>
                        </div>  
                    </div>
                    <div class="confirm-add-wrap">
                        <button class="button-edit-submit" type="submit" name="button_edit_confirm">Xác Nhận Chỉnh sửa</button>
                    </div>
                </form>
                
            </div>
            
        </content>
    </div>
</div>
<script>
    function openSide(){
        const sidebar = document.getElementById("sidebar");
        sidebar.classList.add("sidebar-active") ;

        window.addEventListener("mouseup", function(event) {
            if (event.target != sidebar) {
                sidebar.classList.remove("sidebar-active");
            }
        });

        window.addEventListener("resize", () =>{
            if(window.innerWidth > 414){
                sidebar.classList.add("sidebar-active") ;
            }
        });
    }
</script>

</body>
</html>
