<?php

namespace View\Dish;
use Controller\DishController;
use Model;
// use Model\Dish\DishModel;

$dishController = new DishController();
$listDishes = $dishController->getAllDish();

// session_start();
// if(isset($_SESSION["staff"])){
//     $staff = $_SESSION["staff"];
// //    var_dump($staff);
// } else{
//     header('Location: index.php');
// }
// $tableController = new TableController();
// $tables = $tableController->getAllTable();
// //var_dump($tables);
// $table_id = 1;
// if(isset($_GET['table_id'])){
//     $_SESSION['table_id'] = $_GET['table_id'];
//     $table_id = $_SESSION['table_id'];
// }
// $currenttable = $tableController->getTableById($table_id);
// $grouptable = $tableController->getTableByOtherTable($table_id);
?>


<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="./css/style.css">
    <link rel="stylesheet" href="./css/Dish.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <title>Dishes Managament</title>
</head>
<body>

<div class = "page">
    <header class="header-wrapper">
        <div class="header-group">
            <label> Tên nhà hàng</label>
        </div>

        <div class="header-group">
            <i class='fa-solid fa-user icon-user'></i>
            <span class="header-identity">
                <?php echo "Chu Manh Tien"?>
            </span>
        </div>
    </header>
    <div class="container">
        <aside class="sidebar-wrapper">
            <a href="#" class="sidebar-link">
                <i class="fa-solid fa-table"></i>
                Quản lý Bàn
            </a>
            <a href="#" class="sidebar-link">
                <i class="fa-solid fa-money-bill"></i>
                Quản lý Hóa đơn
            </a>
            <a href="#" class="sidebar-link <?php echo "active"?>">
                <i class="fa-solid fa-utensils"></i>
                Quản lý Món ăn
            </a>
            <a href="#" class="sidebar-link ">
                <i class="fa-solid fa-calendar-check"></i>
                Quản lý Sự kiện
            </a>
            <a href="#" class="sidebar-link">
                <i class="fa-solid fa-chart-column"></i>
                Thống kê kinh doanh
            </a>
        </aside>

        <content class="content-wrapper">
            <nav class="content-nav">
                <?php
                    // $reservetableurl = $_SERVER['PHP_SELF'];
                    // $reservetableurl .= "?reserve";
                    // echo "<a href='$reservetableurl' class='dish-button dish-button-return'>";
                    // echo "Trở lại";
                    // echo "</a>";
                ?>
                <!-- <a href="#" class="dish-button dish-button-return">
                    Trở lại              
                </a> -->
                <form  action="./Dish.php" method="POST">
                    <button type="submit" name="button_add" class="dish-button dish-button-add"> 
                        <i class="fa-regular fa-square-plus"></i>
                        Thêm món ăn   
                    </button>  
                </form>
                <div class="dish-management-title">Danh sách món ăn</d>
                
            </nav>
            <div class="content-main">
                <div class="search-filter-bar">
                    <div class="row search-filter">
                        <div class="search-bar">
                            <form class="search-form">
                                <input type="search" placeholder="search">
                                <button type="submit">
                                    <i class="fa-solid fa-magnifying-glass"></i>
                                </button>
                            </form>
                            
                        </div>
                        <div class="filter-list">
                            <div class="filter-bar">
                                <select class="form-select">
                                    <option>Tất cả</option>
                                    <option>Món khai vị</option>
                                    <option>Món chính</option>
                                    <option>Món tráng miệng</option>
                                </select>
                            </div>
                            <div class="filter-bar">
                                <select class="form-select">
                                    <option>Sắp xếp</option>
                                    <option>Đắt nhất</option>
                                    <option>Rẻ nhất</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="list-dish">
                    <div class="row list-dish-body">
                        <?php
                            foreach($listDishes as $dishItem) {
                                $category_color="red";
                                if ($dishItem['category'] == 'trang_mieng') {
                                    $category_color = "blue";
                                } else if ($dishItem['category'] == 'trang_mieng') {
                                    $category_color = "green";
                                }
                                echo "
                                    <div class='dish-card-wrap'>
                                        <div class='dish-card-product'>
                                            <a class='dish-img-wrap' href=''>
                                                <img src=".$dishItem['image_url'].">
                                            </a>
                                          
                                            <div class='dish-info-wrap'>
                                                <a class='dish-title' title=".$dishItem['name']." href=''>
                                                    ".$dishItem['name']."
                                                </a>
                                                <div class='dish-price'>
                                                    Giá: ".$dishItem['price']. "<sup>vnđ</sup>
                                                </div>
                                                <div class='dish-category'>
                                                    #".$dishItem['category']."
                                                </div>
                                                
                                                <div class='row dish-list-action'>
                                                    <form title='Xem' action='Dish.php' method='GET'>
                                                        <input style='display:none' type='number' name='dish_id' value='".$dishItem['dish_id']."'>
                                                        <button class='dish-view' name='button_view' type='submit'>
                                                            <i class='fa-solid fa-eye'></i>  
                                                        </button>
                                                    </form>
                                                    <form title='Sửa' action='Dish.php' method='GET'>
                                                        <input style='display:none' type='number' name='dish_id' value='".$dishItem['dish_id']."'>
                                                        <button class='dish-edit' name='button_edit' type='submit'>
                                                            <i class='fa-solid fa-pen-to-square'></i>  
                                                        </button>
                                                    </form>
                                                    <div title='Xóa'>
                                                        <button class='dish-delete' onclick='showFormConfirm(".$dishItem['dish_id'].")'>
                                                            <i class='fa-solid fa-eraser'></i>
                                                        </button>
                                                    </div>
                                                  

                                                </div>

                                                <div class='popup' id='confirm-form'>
                                                    <form class='popup-form' action='Dish.php' method='POST'>
                                                        <div class='popup-title'>Bạn có muốn Xóa món ăn này không ?</div>
                                                        <div class='popup-button-x' onclick='hideForm()'>X</div>
                                                        <div class='popup-button-group'>
                                                            <button type='submit' class='popup-button button-yes' name='button_delete'>Có</button>
                                                            <div class='popup-button button-no' onclick='hideForm()'>Không</div>
                                                        </div>
                                                       
                                                        <input style='display:none' type='number' name='dish_delete_id' id='input_delete_id'>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>";
                            } 
                        ?>
                        
                    </div>
                    <div class="pagination">
                        <div class="pre-page">
                            Trang trước
                        </div>
                        <div class="list-page">
                            <ul>
                                <?php 
                                    echo "<li class='list-page-number number-active'>1</li>";
                                    for ($i = 2; $i <= 6; $i++)
                                        echo "<li class='list-page-number'>$i</li>"
                                ?>   
                            </ul>
                        </div>
                        <div class="pre-page">
                            Trang sau
                        </div>
                    </div>
                </div>
            </div>
            
        </content>
    </div>
</div>

<script>
    function showFormConfirm(dish_id) {
        document.getElementById('confirm-form').style.visibility = 'visible';
        document.getElementById('input_delete_id').value = dish_id;
    }
    function hideForm() {
        document.getElementById('confirm-form').style.visibility = 'hidden';
    }
</script>

</body>

</html>
