<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="css/order.css" />
		<script
			src="https://kit.fontawesome.com/48b5735cbc.js"
			crossorigin="anonymous"
		></script>
		<title>Food Store</title>
	</head>
	<body>
		<div class="top-bar">
			<img
				src="https://static.vecteezy.com/system/resources/previews/000/656/608/original/vector-restaurant-badge-and-logo-good-for-print.jpg"
				alt="logo"
			/>
			<div class="navbar">
				<a href="index.php">Trang chủ</a>
				<a href="intro.php">Giới thiệu</a>
				<a  class="pressing-btn" href="#">Đặt bàn</a>
				<a href="menu.php">Thực đơn</a>
				<a href="news.php">Tin tức</a>
				<a href="contact.php">Liên hệ</a>
			</div>
			<i class="fa-solid fa-bars" onclick="toggleMenu();"></i>
		</div>

		<div class="first-img">
			<img
				src="https://homebbq.thietkewebsitemienphi.com/wp-content/uploads/2018/02/banner-234.jpg"
				alt=""
			/>
		</div>

    <div class="order">
			<div class="text-box-3">
				<h1>Set Table</h1>
				<p class="no-num">
					Quý khách vui lòng đặt bàn trước để có trải nghiệm thưởng thức ẩm thực
					tốt nhất tại Sun Homes BBQ.
				</p>
				<p class="no-num">Gợi ý đặt bàn:</p>
				<p><i class="fa-solid fa-angle-right i-2nd"></i> Đi 1 người: đặt bàn đơn</p>
				<hr />
				<p><i class="fa-solid fa-angle-right i-2nd"></i> Đi 2 người: đặt bàn đôi</p>
				<hr />
				<p>
					<i class="fa-solid fa-angle-right i-2nd"></i> Đi nhóm 4-6 người: đặt bàn 6
					người.
				</p>
				<hr />
				<p>
					<i class="fa-solid fa-angle-right i-2nd"></i> Đi nhóm 6-12 người: đặt bàn
					dài
				</p>
				<hr />
				<p>
					<i class="fa-solid fa-angle-right i-2nd"></i> Đi nhóm >12 người: gọi trực
					tiếp Hotline: 0909.009.009
				</p>
				<hr />
			</div>

      <div class="infor">
				<input type="text" placeholder="Tên của bạn..." />
				<input type="text" placeholder="Số điện thoại..." />
				<input type="number" placeholder="Số người ăn..." />
				<input type="date" />
				<input class="checkbox" type="checkbox" /><span>08:00</span>
				<input class="checkbox" type="checkbox" /><span>10:00</span>
				<input class="checkbox" type="checkbox" /><span>12:00</span>
				<input class="checkbox" type="checkbox" /><span>14:00</span>
				<input class="checkbox" type="checkbox" /><span>16:00</span>
				<button onclick="alert('Order was successfully!');"><b>ĐẶT BÀN</b></button>
			</div>
		</div>

		<script>
			const toggleMenu = () => {
				const menu = document.querySelector('.navbar');
				if (menu.style.visibility == 'hidden') menu.style.visibility = 'visible';
				else menu.style.visibility = 'hidden';
			}
		</script>
  </body>
</html>